/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.115
 * Generated at: 2026-03-06 20:53:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.hotel.model.enums.RoomType;

public final class addReservation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.hotel.model.enums.RoomType");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    RoomType[] roomTypes = (RoomType[]) request.getAttribute("roomTypes");
    if (roomTypes == null) {
        roomTypes = RoomType.values();
    }
    String role = String.valueOf(session.getAttribute("role"));
    boolean canAccessReports = "ADMIN".equalsIgnoreCase(role) || "MANAGER".equalsIgnoreCase(role);
    boolean canManageReservations = "ADMIN".equalsIgnoreCase(role) || "RECEPTION".equalsIgnoreCase(role);

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>Add Reservation</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"app-shell\">\r\n");
      out.write("    <header class=\"topbar no-print\">\r\n");
      out.write("        <div class=\"topbar-main\">\r\n");
      out.write("            <div class=\"brand-block\">\r\n");
      out.write("                <span class=\"eyebrow\">Reservation Workflow</span>\r\n");
      out.write("                <div class=\"brand\">Guest Booking Intake</div>\r\n");
      out.write("                <div class=\"brand-sub\">Create complete reservation records in one step</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"brand-meta\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('|');
      out.write(' ');
      out.print( role );
      out.write("</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <nav class=\"nav-links\">\r\n");
      out.write("            <a class=\"btn btn-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/dashboard\">Dashboard</a>\r\n");
      out.write("            <a class=\"btn btn-link active\" href=\"");
      out.print(request.getContextPath());
      out.write("/reservation/add\">New Reservation</a>\r\n");
      out.write("            <a class=\"btn btn-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/reservation\">View Reservations</a>\r\n");
      out.write("            ");
 if (canManageReservations) { 
      out.write("\r\n");
      out.write("            <a class=\"btn btn-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/bill\">Calculate Bill</a>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            ");
 if (canAccessReports) { 
      out.write("\r\n");
      out.write("            <a class=\"btn btn-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/report\">Reports</a>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            <a class=\"btn btn-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/help\">Help</a>\r\n");
      out.write("            <a class=\"btn btn-danger\" href=\"");
      out.print(request.getContextPath());
      out.write("/logout\">Logout</a>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"page-header\">\r\n");
      out.write("        <h1 class=\"page-title\">Add Reservation</h1>\r\n");
      out.write("        <p class=\"page-subtitle\">Capture guest profile, stay duration, and room type with validated booking details.</p>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    ");
 if (request.getAttribute("error") != null) { 
      out.write("\r\n");
      out.write("    <div class=\"alert alert-danger\">");
      out.print( request.getAttribute("error") );
      out.write("</div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <section class=\"grid-2\">\r\n");
      out.write("        <article class=\"card\">\r\n");
      out.write("            <h2 class=\"section-title\">Guest and Booking Information</h2>\r\n");
      out.write("            <p class=\"section-subtitle\">Fill all required fields to generate a valid reservation record.</p>\r\n");
      out.write("            <form class=\"form-grid\" action=\"");
      out.print(request.getContextPath());
      out.write("/reservation/add\" method=\"post\" onsubmit=\"return validateReservationForm()\">\r\n");
      out.write("                <div class=\"field\">\r\n");
      out.write("                    <label for=\"guestName\">Guest Name</label>\r\n");
      out.write("                    <input id=\"guestName\" type=\"text\" name=\"guestName\" value=\"");
      out.print( request.getParameter("guestName") != null ? request.getParameter("guestName") : "" );
      out.write("\" placeholder=\"Full name\" required/>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"field\">\r\n");
      out.write("                    <label for=\"contactNo\">Contact Number</label>\r\n");
      out.write("                    <input id=\"contactNo\" type=\"text\" name=\"contactNo\" value=\"");
      out.print( request.getParameter("contactNo") != null ? request.getParameter("contactNo") : "" );
      out.write("\" placeholder=\"10-12 digits\" required/>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"field full-width\">\r\n");
      out.write("                    <label for=\"address\">Address</label>\r\n");
      out.write("                    <input id=\"address\" type=\"text\" name=\"address\" value=\"");
      out.print( request.getParameter("address") != null ? request.getParameter("address") : "" );
      out.write("\" placeholder=\"Street, city, country\" required/>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"field\">\r\n");
      out.write("                    <label for=\"email\">Email</label>\r\n");
      out.write("                    <input id=\"email\" type=\"email\" name=\"email\" value=\"");
      out.print( request.getParameter("email") != null ? request.getParameter("email") : "" );
      out.write("\" placeholder=\"guest@example.com\"/>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"field\">\r\n");
      out.write("                    <label for=\"roomType\">Room Type</label>\r\n");
      out.write("                    <select id=\"roomType\" name=\"roomType\" required>\r\n");
      out.write("                        <option value=\"\">Select room type</option>\r\n");
      out.write("                        ");

                            String selectedRoomType = request.getParameter("roomType");
                            for (RoomType roomType : roomTypes) {
                        
      out.write("\r\n");
      out.write("                        <option value=\"");
      out.print( roomType.name() );
      out.write('"');
      out.write(' ');
      out.print( roomType.name().equals(selectedRoomType) ? "selected" : "" );
      out.write('>');
      out.print( roomType.name() );
      out.write("</option>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"field\">\r\n");
      out.write("                    <label for=\"checkInDate\">Check-In Date</label>\r\n");
      out.write("                    <input id=\"checkInDate\" type=\"date\" name=\"checkInDate\" value=\"");
      out.print( request.getParameter("checkInDate") != null ? request.getParameter("checkInDate") : "" );
      out.write("\" required/>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"field\">\r\n");
      out.write("                    <label for=\"checkOutDate\">Check-Out Date</label>\r\n");
      out.write("                    <input id=\"checkOutDate\" type=\"date\" name=\"checkOutDate\" value=\"");
      out.print( request.getParameter("checkOutDate") != null ? request.getParameter("checkOutDate") : "" );
      out.write("\" required/>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"field\">\r\n");
      out.write("                    <label for=\"numGuests\">Number of Guests</label>\r\n");
      out.write("                    <input id=\"numGuests\" type=\"number\" name=\"numGuests\" value=\"");
      out.print( request.getParameter("numGuests") != null ? request.getParameter("numGuests") : "" );
      out.write("\" min=\"1\" required/>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"field full-width\">\r\n");
      out.write("                    <label for=\"specialRequests\">Special Requests</label>\r\n");
      out.write("                    <textarea id=\"specialRequests\" name=\"specialRequests\" placeholder=\"Airport pickup, extra bed, dietary preferences, etc.\">");
      out.print( request.getParameter("specialRequests") != null ? request.getParameter("specialRequests") : "" );
      out.write("</textarea>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"action-row full-width\">\r\n");
      out.write("                    <button class=\"btn btn-primary\" type=\"submit\">Create Reservation</button>\r\n");
      out.write("                    <a class=\"btn btn-secondary\" href=\"");
      out.print(request.getContextPath());
      out.write("/dashboard\">Back to Dashboard</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </article>\r\n");
      out.write("\r\n");
      out.write("        <aside class=\"card no-print\">\r\n");
      out.write("            <h2 class=\"section-title\">Entry Checklist</h2>\r\n");
      out.write("            <ul class=\"help-list\">\r\n");
      out.write("                <li>Confirm legal guest name and primary contact number.</li>\r\n");
      out.write("                <li>Verify check-out date is after the check-in date.</li>\r\n");
      out.write("                <li>Choose the correct room type before submitting.</li>\r\n");
      out.write("                <li>Record special requests for front desk coordination.</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </aside>\r\n");
      out.write("    </section>\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/validation.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
