/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.115
 * Generated at: 2026-03-06 20:53:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import java.util.Map;
import com.hotel.model.Reservation;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("com.hotel.model.Reservation");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    Map<String, Object> stats = (Map<String, Object>) request.getAttribute("stats");
    List<Reservation> recent = stats == null ? null : (List<Reservation>) stats.get("recentReservations");
    Object totalReservations = stats != null ? stats.get("totalReservations") : 0;
    Object totalRevenue = stats != null ? stats.get("totalRevenue") : 0;
    Object occupancyRate = stats != null ? stats.get("occupancyRate") : 0;
    String role = String.valueOf(session.getAttribute("role"));
    boolean canAccessReports = "ADMIN".equalsIgnoreCase(role) || "MANAGER".equalsIgnoreCase(role);
    boolean canManageReservations = "ADMIN".equalsIgnoreCase(role) || "RECEPTION".equalsIgnoreCase(role);

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>Dashboard</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"app-shell\">\r\n");
      out.write("    <header class=\"topbar no-print\">\r\n");
      out.write("        <div class=\"topbar-main\">\r\n");
      out.write("            <div class=\"brand-block\">\r\n");
      out.write("                <span class=\"eyebrow\">Operations Suite</span>\r\n");
      out.write("                <div class=\"brand\">Harbor View Hotel</div>\r\n");
      out.write("                <div class=\"brand-sub\">Reservation management console</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"brand-meta\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('|');
      out.write(' ');
      out.print( role );
      out.write("</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <nav class=\"nav-links\">\r\n");
      out.write("            <a class=\"btn btn-link active\" href=\"");
      out.print(request.getContextPath());
      out.write("/dashboard\">Dashboard</a>\r\n");
      out.write("            ");
 if (canManageReservations) { 
      out.write("\r\n");
      out.write("            <a class=\"btn btn-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/reservation/add\">New Reservation</a>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            <a class=\"btn btn-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/reservation\">View Reservations</a>\r\n");
      out.write("            ");
 if (canManageReservations) { 
      out.write("\r\n");
      out.write("            <a class=\"btn btn-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/bill\">Calculate Bill</a>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            ");
 if (canAccessReports) { 
      out.write("\r\n");
      out.write("            <a class=\"btn btn-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/report\">Reports</a>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            <a class=\"btn btn-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/help\">Help</a>\r\n");
      out.write("            <a class=\"btn btn-danger\" href=\"");
      out.print(request.getContextPath());
      out.write("/logout\">Logout</a>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"page-header\">\r\n");
      out.write("        <h1 class=\"page-title\">Operations Dashboard</h1>\r\n");
      out.write("        <p class=\"page-subtitle\">Welcome, <strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong>. Track reservation activity, room occupancy, and revenue performance from one place.</p>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    ");
 if (session.getAttribute("message") != null) { 
      out.write("\r\n");
      out.write("    <div class=\"alert alert-success\">");
      out.print( session.getAttribute("message") );
      out.write("</div>\r\n");
      out.write("    ");
 session.removeAttribute("message"); 
      out.write("\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
 if (session.getAttribute("error") != null) { 
      out.write("\r\n");
      out.write("    <div class=\"alert alert-danger\">");
      out.print( session.getAttribute("error") );
      out.write("</div>\r\n");
      out.write("    ");
 session.removeAttribute("error"); 
      out.write("\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
 if (request.getAttribute("error") != null) { 
      out.write("\r\n");
      out.write("    <div class=\"alert alert-danger\">");
      out.print( request.getAttribute("error") );
      out.write("</div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <section class=\"card no-print\">\r\n");
      out.write("        <h2 class=\"section-title\">Quick Actions</h2>\r\n");
      out.write("        <p class=\"section-subtitle\">Start a task directly from your role-approved workflows.</p>\r\n");
      out.write("        <div class=\"quick-grid\">\r\n");
      out.write("            ");
 if (canManageReservations) { 
      out.write("\r\n");
      out.write("            <a class=\"quick-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/reservation/add\">\r\n");
      out.write("                <strong>Create Reservation</strong>\r\n");
      out.write("                <span>Capture a new guest booking.</span>\r\n");
      out.write("            </a>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            <a class=\"quick-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/reservation\">\r\n");
      out.write("                <strong>View Reservations</strong>\r\n");
      out.write("                <span>Search, inspect, and manage records.</span>\r\n");
      out.write("            </a>\r\n");
      out.write("            ");
 if (canManageReservations) { 
      out.write("\r\n");
      out.write("            <a class=\"quick-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/bill\">\r\n");
      out.write("                <strong>Generate Bill</strong>\r\n");
      out.write("                <span>Produce and print payment details.</span>\r\n");
      out.write("            </a>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            ");
 if (canAccessReports) { 
      out.write("\r\n");
      out.write("            <a class=\"quick-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/report\">\r\n");
      out.write("                <strong>Open Reports</strong>\r\n");
      out.write("                <span>Review occupancy and revenue trends.</span>\r\n");
      out.write("            </a>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            <a class=\"quick-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/help\">\r\n");
      out.write("                <strong>Help Center</strong>\r\n");
      out.write("                <span>Check role guide and process notes.</span>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"card\">\r\n");
      out.write("        <h2 class=\"section-title\">Key Metrics</h2>\r\n");
      out.write("        <p class=\"section-subtitle\">Current operational snapshot generated from reservation data.</p>\r\n");
      out.write("        <div class=\"metric-grid\">\r\n");
      out.write("            <article class=\"metric-card\">\r\n");
      out.write("                <span class=\"label\">Total Reservations</span>\r\n");
      out.write("                <span class=\"value\">");
      out.print( totalReservations );
      out.write("</span>\r\n");
      out.write("            </article>\r\n");
      out.write("            <article class=\"metric-card\">\r\n");
      out.write("                <span class=\"label\">Total Revenue</span>\r\n");
      out.write("                <span class=\"value\">$");
      out.print( totalRevenue );
      out.write("</span>\r\n");
      out.write("            </article>\r\n");
      out.write("            <article class=\"metric-card\">\r\n");
      out.write("                <span class=\"label\">Occupancy Rate</span>\r\n");
      out.write("                <span class=\"value\">");
      out.print( occupancyRate );
      out.write("%</span>\r\n");
      out.write("            </article>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"card\">\r\n");
      out.write("        <h2 class=\"section-title\">Recent Reservations</h2>\r\n");
      out.write("        <p class=\"section-subtitle\">Latest bookings to review and process quickly.</p>\r\n");
      out.write("        <div class=\"table-shell\">\r\n");
      out.write("            <table>\r\n");
      out.write("                <thead>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>ID</th>\r\n");
      out.write("                    <th>Reservation No</th>\r\n");
      out.write("                    <th>Guest</th>\r\n");
      out.write("                    <th>Room</th>\r\n");
      out.write("                    <th>Total</th>\r\n");
      out.write("                    <th>Actions</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                ");

                    if (recent != null && !recent.isEmpty()) {
                        for (Reservation r : recent) {
                
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>");
      out.print( r.getId() );
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print( r.getReservationNo() );
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print( r.getGuestName() );
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print( r.getRoomType() );
      out.write("</td>\r\n");
      out.write("                    <td>$");
      out.print( r.getTotalAmount() );
      out.write("</td>\r\n");
      out.write("                    <td class=\"actions\">\r\n");
      out.write("                        <a class=\"btn btn-secondary btn-sm\" href=\"");
      out.print(request.getContextPath());
      out.write("/reservation/view?id=");
      out.print(r.getId());
      out.write("\">View</a>\r\n");
      out.write("                        ");
 if (canManageReservations) { 
      out.write("\r\n");
      out.write("                        <a class=\"btn btn-secondary btn-sm\" href=\"");
      out.print(request.getContextPath());
      out.write("/bill?reservationId=");
      out.print(r.getId());
      out.write("\">Bill</a>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                ");

                        }
                    } else {
                
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td colspan=\"6\" class=\"empty-state\">No reservations yet. Click \"New Reservation\" to create the first booking.</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
