/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.115
 * Generated at: 2026-03-06 21:01:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class help_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>Help</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

    String role = String.valueOf(session.getAttribute("role"));
    boolean canAccessReports = "ADMIN".equalsIgnoreCase(role) || "MANAGER".equalsIgnoreCase(role);
    boolean canManageReservations = "ADMIN".equalsIgnoreCase(role) || "RECEPTION".equalsIgnoreCase(role);

      out.write("\r\n");
      out.write("<div class=\"app-shell\">\r\n");
      out.write("    <header class=\"topbar no-print\">\r\n");
      out.write("        <div class=\"topbar-main\">\r\n");
      out.write("            <div class=\"brand-block\">\r\n");
      out.write("                <span class=\"eyebrow\">Support</span>\r\n");
      out.write("                <div class=\"brand\">Help Center</div>\r\n");
      out.write("                <div class=\"brand-sub\">Operational guidance and role-based usage notes</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"brand-meta\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('|');
      out.write(' ');
      out.print( role );
      out.write("</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <nav class=\"nav-links\">\r\n");
      out.write("            <a class=\"btn btn-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/dashboard\">Dashboard</a>\r\n");
      out.write("            <a class=\"btn btn-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/reservation\">Reservations</a>\r\n");
      out.write("            ");
 if (canManageReservations) { 
      out.write("\r\n");
      out.write("            <a class=\"btn btn-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/bill\">Billing</a>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            ");
 if (canAccessReports) { 
      out.write("\r\n");
      out.write("            <a class=\"btn btn-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/report\">Reports</a>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            <a class=\"btn btn-link active\" href=\"");
      out.print(request.getContextPath());
      out.write("/help\">Help</a>\r\n");
      out.write("            <a class=\"btn btn-danger\" href=\"");
      out.print(request.getContextPath());
      out.write("/logout\">Logout</a>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"page-header\">\r\n");
      out.write("        <h1 class=\"page-title\">Help and Usage Guide</h1>\r\n");
      out.write("        <p class=\"page-subtitle\">Use these reference steps for accurate operation during demos and final evaluation.</p>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"card no-print\">\r\n");
      out.write("        <h2 class=\"section-title\">Quick Orientation</h2>\r\n");
      out.write("        <div class=\"quick-grid\">\r\n");
      out.write("            <div class=\"quick-item\">\r\n");
      out.write("                <strong>Step 1</strong>\r\n");
      out.write("                <span>Login with the correct role account credentials.</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"quick-item\">\r\n");
      out.write("                <strong>Step 2</strong>\r\n");
      out.write("                <span>Create and validate reservation data carefully.</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"quick-item\">\r\n");
      out.write("                <strong>Step 3</strong>\r\n");
      out.write("                <span>Generate bills and review totals before printing.</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"quick-item\">\r\n");
      out.write("                <strong>Step 4</strong>\r\n");
      out.write("                <span>Review reports (manager/admin) for final analysis.</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"card\">\r\n");
      out.write("        <h2 class=\"section-title\">Core Workflow</h2>\r\n");
      out.write("        <ol class=\"help-list\">\r\n");
      out.write("            <li>Login using provided credentials.</li>\r\n");
      out.write("            <li>Reception role: create, view, update, and delete reservations.</li>\r\n");
      out.write("            <li>Reception role: generate bills from the Calculate Bill page by reservation ID.</li>\r\n");
      out.write("            <li>Manager/Admin role: review occupancy and revenue trends from the Reports page.</li>\r\n");
      out.write("            <li>Use logout after completing operations to end the session safely.</li>\r\n");
      out.write("        </ol>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"card\">\r\n");
      out.write("        <h2 class=\"section-title\">Quality Checklist</h2>\r\n");
      out.write("        <div class=\"stack\">\r\n");
      out.write("            <p>1. Keep guest details complete and accurate before saving.</p>\r\n");
      out.write("            <p>2. Verify check-in/check-out dates and number of guests.</p>\r\n");
      out.write("            <p>3. Confirm totals and print bill only after reviewing values.</p>\r\n");
      out.write("            <p>4. Use search before deleting to avoid removing wrong records.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"card\">\r\n");
      out.write("        <h2 class=\"section-title\">Role Access Matrix</h2>\r\n");
      out.write("        <div class=\"table-shell\">\r\n");
      out.write("            <table>\r\n");
      out.write("                <thead>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>Page / Feature</th>\r\n");
      out.write("                    <th>Reception</th>\r\n");
      out.write("                    <th>Manager</th>\r\n");
      out.write("                    <th>Admin</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>Dashboard</td>\r\n");
      out.write("                    <td>Yes</td>\r\n");
      out.write("                    <td>Yes</td>\r\n");
      out.write("                    <td>Yes</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>Add / Update / Delete Reservation</td>\r\n");
      out.write("                    <td>Yes</td>\r\n");
      out.write("                    <td>No</td>\r\n");
      out.write("                    <td>Yes</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>Calculate &amp; Print Bill</td>\r\n");
      out.write("                    <td>Yes</td>\r\n");
      out.write("                    <td>No</td>\r\n");
      out.write("                    <td>Yes</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>View Reservations</td>\r\n");
      out.write("                    <td>Yes</td>\r\n");
      out.write("                    <td>Yes (Read-only)</td>\r\n");
      out.write("                    <td>Yes</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>Reports + Export</td>\r\n");
      out.write("                    <td>No</td>\r\n");
      out.write("                    <td>Yes</td>\r\n");
      out.write("                    <td>Yes</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
