/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.115
 * Generated at: 2026-03-06 21:00:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Map;

public final class reports_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.util.Map");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    Map<String, Object> occupancy = (Map<String, Object>) request.getAttribute("occupancy");
    Map<String, Object> revenue = (Map<String, Object>) request.getAttribute("revenue");
    String role = String.valueOf(session.getAttribute("role"));
    boolean canAccessReports = "ADMIN".equalsIgnoreCase(role) || "MANAGER".equalsIgnoreCase(role);
    boolean canManageReservations = "ADMIN".equalsIgnoreCase(role) || "RECEPTION".equalsIgnoreCase(role);
    double occupancyRate = 0.0;
    if (occupancy != null && occupancy.get("occupancyRate") instanceof Number) {
        occupancyRate = ((Number) occupancy.get("occupancyRate")).doubleValue();
    }
    if (occupancyRate < 0) {
        occupancyRate = 0.0;
    }
    if (occupancyRate > 100) {
        occupancyRate = 100.0;
    }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>Reports</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"app-shell\">\r\n");
      out.write("    <header class=\"topbar no-print\">\r\n");
      out.write("        <div class=\"topbar-main\">\r\n");
      out.write("            <div class=\"brand-block\">\r\n");
      out.write("                <span class=\"eyebrow\">Analytics</span>\r\n");
      out.write("                <div class=\"brand\">Performance Reports</div>\r\n");
      out.write("                <div class=\"brand-sub\">Occupancy and revenue insight dashboard</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"brand-meta\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('|');
      out.write(' ');
      out.print( role );
      out.write("</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <nav class=\"nav-links\">\r\n");
      out.write("            <a class=\"btn btn-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/dashboard\">Dashboard</a>\r\n");
      out.write("            <a class=\"btn btn-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/reservation\">Reservations</a>\r\n");
      out.write("            ");
 if (canManageReservations) { 
      out.write("\r\n");
      out.write("            <a class=\"btn btn-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/bill\">Billing</a>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            <a class=\"btn btn-link active\" href=\"");
      out.print(request.getContextPath());
      out.write("/report\">Reports</a>\r\n");
      out.write("            <a class=\"btn btn-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/help\">Help</a>\r\n");
      out.write("            <a class=\"btn btn-danger\" href=\"");
      out.print(request.getContextPath());
      out.write("/logout\">Logout</a>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"page-header\">\r\n");
      out.write("        <h1 class=\"page-title\">Reports</h1>\r\n");
      out.write("        <p class=\"page-subtitle\">Occupancy and revenue performance generated from current reservation records.</p>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"action-row no-print\">\r\n");
      out.write("        <a class=\"btn btn-secondary\" href=\"");
      out.print(request.getContextPath());
      out.write("/report?export=csv\">Export CSV</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    ");
 if (request.getAttribute("error") != null) { 
      out.write("\r\n");
      out.write("    <div class=\"alert alert-danger\">");
      out.print( request.getAttribute("error") );
      out.write("</div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <section class=\"card no-print\">\r\n");
      out.write("        <h2 class=\"section-title\">Report Summary</h2>\r\n");
      out.write("        <div class=\"quick-grid\">\r\n");
      out.write("            <div class=\"quick-item\">\r\n");
      out.write("                <strong>Occupancy Rate</strong>\r\n");
      out.write("                <span>");
      out.print( String.format("%.2f", occupancyRate) );
      out.write("% active room usage.</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"quick-item\">\r\n");
      out.write("                <strong>Total Revenue</strong>\r\n");
      out.write("                <span>$");
      out.print( revenue != null ? revenue.get("totalRevenue") : 0 );
      out.write(" collected.</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"quick-item\">\r\n");
      out.write("                <strong>Reservation Volume</strong>\r\n");
      out.write("                <span>");
      out.print( revenue != null ? revenue.get("reservationCount") : 0 );
      out.write(" reservations in report scope.</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");
 if (canAccessReports) { 
      out.write("\r\n");
      out.write("            <div class=\"quick-item\">\r\n");
      out.write("                <strong>Export Ready</strong>\r\n");
      out.write("                <span>Download CSV for external review and submission.</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"grid-2\">\r\n");
      out.write("        <article class=\"card\">\r\n");
      out.write("            <h2 class=\"section-title\">Occupancy Report</h2>\r\n");
      out.write("            <div class=\"stack\">\r\n");
      out.write("                <div class=\"bill-item\">\r\n");
      out.write("                    <strong>Total Rooms</strong>\r\n");
      out.write("                    <span>");
      out.print( occupancy != null ? occupancy.get("totalRooms") : 0 );
      out.write("</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"bill-item\">\r\n");
      out.write("                    <strong>Occupied Rooms</strong>\r\n");
      out.write("                    <span>");
      out.print( occupancy != null ? occupancy.get("occupiedRooms") : 0 );
      out.write("</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"bill-item\">\r\n");
      out.write("                    <strong>Available Rooms</strong>\r\n");
      out.write("                    <span>");
      out.print( occupancy != null ? occupancy.get("availableRooms") : 0 );
      out.write("</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"bill-item\">\r\n");
      out.write("                    <strong>Occupancy Rate</strong>\r\n");
      out.write("                    <span>");
      out.print( String.format("%.2f", occupancyRate) );
      out.write("%</span>\r\n");
      out.write("                    <div class=\"progress-wrap\">\r\n");
      out.write("                        <div class=\"progress-track\">\r\n");
      out.write("                            <div class=\"progress-bar\" style=\"width:");
      out.print( String.format(java.util.Locale.US, "%.2f", occupancyRate) );
      out.write("%;\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </article>\r\n");
      out.write("\r\n");
      out.write("        <article class=\"card\">\r\n");
      out.write("            <h2 class=\"section-title\">Revenue Report</h2>\r\n");
      out.write("            <div class=\"stack\">\r\n");
      out.write("                <div class=\"bill-item\">\r\n");
      out.write("                    <strong>Total Revenue</strong>\r\n");
      out.write("                    <span>$");
      out.print( revenue != null ? revenue.get("totalRevenue") : 0 );
      out.write("</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"bill-item\">\r\n");
      out.write("                    <strong>Reservation Count</strong>\r\n");
      out.write("                    <span>");
      out.print( revenue != null ? revenue.get("reservationCount") : 0 );
      out.write("</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </article>\r\n");
      out.write("    </section>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
